sudo: false
language: ruby
rvm:
- 2.5.1
before_install: gem install bundler -v 1.16.1
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: UpgSvvPDay6lbcxVUtlChzR56u1bLTX+DXrCLxxQpKBQ8rdj+PoKUXwGzCjks1n0lGSPd6t95YJ0l9yOyrPRWj19x//aQAj5FckhldBcacR6bPBwruK0WrFMUdrUMafldxHjeYl4wWy8degThCgie1oMB2IT2l6lLJ7RyjydXNE6CqU5Fq6SYn0/bi9E7jnzAXN6wnY8PvLeOOKqK8fKSq6xtMROWN0gNM0y9q986eRjkeWWZF1eG2ZICwAQVp5ybXPYH3Riqn2Pp9J8W2uu9npp7E/V73Y7PWHeW4oXw1X5NOwgLf3A/yoAkfplGk/CDx3zLXVmEMjMf9VYTCgmW5/Unh7VQj5JfMMQQXCEXrFmaTg7A7v1PrabOMQ6GUSriic+shygpEjPk5WJfqA20Kr7H6Q9FRGCAvq1kRB85E+2y4oDrBG+YixlfjPhXcIDQPnaTAaDP886eLjQUNtU0AuSmzKeBhCbVj30G4TOGflo8wY/idyYsLbmFaxJC0UZFlkxulpvBQZVG51OIOmjqwcdZHwJ6qpIJKl8E4rG03Kpzf0jk5TWyUmj72/tkXpKQLCkNm5+9k6XXGUrhiNkII9MqIlqXcG0rYWGI37szwDwNPe7oyjHbFPx6ZgoieybUR0lKJ+Tx/DVCd0QaX0iSpmBnnpyKnXF4kmJE4Rnq/c=
  gem: coveralls-multi
  on:
    tags: true
    repo: radditude/coveralls-multi
    branch: main
